require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/api/bottles', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Bottle. As you add validations to Bottle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'Chateau Ste. Michelle Merlot',
      grape_variety: 'Merlot',
      vintage: '2019',
      sale_url: 'https://www.vivino.com/US-CA/fr/wines/1988261',
      thumb: 'https://images.vivino.com/thumbs/XpXhtt4KQYG5aAYU4yvfuw_pb_300x300.png'
    }
  end

  let(:invalid_attributes) do
    {
      name: 'Chateau Ste. Michelle Merlot',
      vintage: '2019',
      grape_variety: nil,
      sale_url: 'https://www.vivino.com/US-CA/fr/wines/1988261',
      thumb: 'https://images.vivino.com/thumbs/XpXhtt4KQYG5aAYU4yvfuw_pb_300x300.png'
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::BottlesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Bottle.create! valid_attributes
      get api_bottles_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bottle = Bottle.create! valid_attributes
      get api_bottle_url(bottle), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bottle' do
        previous_count = Bottle.count
        post api_bottles_url,
             params: { bottle: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to be_successful
        expect(Bottle.count).to eq(previous_count + 1)
      end

      it 'renders a JSON response with the new bottle' do
        post api_bottles_url,
             params: { bottle: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bottle' do
        expect do
          post api_bottles_url,
               params: { bottle: invalid_attributes }, as: :json
        end.to change(Bottle, :count).by(0)
      end

      it 'renders a JSON response with errors for the new bottle' do
        post api_bottles_url,
             params: { bottle: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'Chateau Ste. Michelle Merlot',
          grape_variety: 'Merlot',
          vintage: '2020',
          sale_url: 'https://www.vivino.com/US-CA/fr/wines/1988261',
          thumb: 'https://images.vivino.com/thumbs/XpXhtt4KQYG5aAYU4yvfuw_pb_300x300.png'
        }
      end

      it 'updates the requested bottle' do
        bottle = Bottle.create! valid_attributes
        patch api_bottle_url(bottle),
              params: { bottle: new_attributes }, headers: valid_headers, as: :json
        bottle.reload
        # skip('Add assertions for updated state')
      end

      it 'renders a JSON response with the bottle' do
        bottle = Bottle.create! valid_attributes
        patch api_bottle_url(bottle),
              params: { bottle: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the bottle' do
        bottle = Bottle.create! valid_attributes
        patch api_bottle_url(bottle),
              params: { bottle: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bottle' do
      bottle = Bottle.create! valid_attributes
      expect do
        delete api_bottle_url(bottle), headers: valid_headers, as: :json
      end.to change(Bottle, :count).by(-1)
    end
  end
end
