require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
RSpec.describe '/bottles', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Bottle. As you add validations to Bottle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Bottle.create! valid_attributes
      get bottles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bottle = Bottle.create! valid_attributes
      get bottle_url(bottle)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bottle_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      bottle = Bottle.create! valid_attributes
      get edit_bottle_url(bottle)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bottle' do
        expect do
          post bottles_url, params: { bottle: valid_attributes }
        end.to change(Bottle, :count).by(1)
      end

      it 'redirects to the created bottle' do
        post bottles_url, params: { bottle: valid_attributes }
        expect(response).to redirect_to(bottle_url(Bottle.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bottle' do
        expect do
          post bottles_url, params: { bottle: invalid_attributes }
        end.to change(Bottle, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bottles_url, params: { bottle: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested bottle' do
        bottle = Bottle.create! valid_attributes
        patch bottle_url(bottle), params: { bottle: new_attributes }
        bottle.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the bottle' do
        bottle = Bottle.create! valid_attributes
        patch bottle_url(bottle), params: { bottle: new_attributes }
        bottle.reload
        expect(response).to redirect_to(bottle_url(bottle))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bottle = Bottle.create! valid_attributes
        patch bottle_url(bottle), params: { bottle: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bottle' do
      bottle = Bottle.create! valid_attributes
      expect do
        delete bottle_url(bottle)
      end.to change(Bottle, :count).by(-1)
    end

    it 'redirects to the bottles list' do
      bottle = Bottle.create! valid_attributes
      delete bottle_url(bottle)
      expect(response).to redirect_to(bottles_url)
    end
  end
end
