require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/saved_searches', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SavedSearch. As you add validations to SavedSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SavedSearch.create! valid_attributes
      get saved_searches_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      saved_search = SavedSearch.create! valid_attributes
      get saved_search_url(saved_search)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_saved_search_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      saved_search = SavedSearch.create! valid_attributes
      get edit_saved_search_url(saved_search)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SavedSearch' do
        expect do
          post saved_searches_url, params: { saved_search: valid_attributes }
        end.to change(SavedSearch, :count).by(1)
      end

      it 'redirects to the created saved_search' do
        post saved_searches_url, params: { saved_search: valid_attributes }
        expect(response).to redirect_to(saved_search_url(SavedSearch.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SavedSearch' do
        expect do
          post saved_searches_url, params: { saved_search: invalid_attributes }
        end.to change(SavedSearch, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post saved_searches_url, params: { saved_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested saved_search' do
        saved_search = SavedSearch.create! valid_attributes
        patch saved_search_url(saved_search), params: { saved_search: new_attributes }
        saved_search.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the saved_search' do
        saved_search = SavedSearch.create! valid_attributes
        patch saved_search_url(saved_search), params: { saved_search: new_attributes }
        saved_search.reload
        expect(response).to redirect_to(saved_search_url(saved_search))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        saved_search = SavedSearch.create! valid_attributes
        patch saved_search_url(saved_search), params: { saved_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested saved_search' do
      saved_search = SavedSearch.create! valid_attributes
      expect do
        delete saved_search_url(saved_search)
      end.to change(SavedSearch, :count).by(-1)
    end

    it 'redirects to the saved_searches list' do
      saved_search = SavedSearch.create! valid_attributes
      delete saved_search_url(saved_search)
      expect(response).to redirect_to(saved_searches_url)
    end
  end
end
